// tailwind.config.js
// Generated by AI

/** @type {import('tailwindcss').Config} */
export default {
  // The 'content' array tells Tailwind CSS where to look for your HTML and JavaScript/TypeScript files
  // that use Tailwind classes. Tailwind will then scan these files and generate only the CSS
  // that is actually used, leading to smaller production bundles.
  content: [
    "./index.html",          // Include your main HTML file
    "./src/**/*.{js,ts,jsx,tsx}", // Scan all JS, TS, JSX, TSX files in the src/ directory and its subdirectories
  ],
  // The 'theme' section is where you customize Tailwind's default design system.
  // You can extend existing values or define your own custom colors, fonts, spacing, etc.
  theme: {
    extend: {
      // Example: extend default colors
      // colors: {
      //   'custom-blue': '#243c5a',
      // },
    },
  },
  // The 'plugins' array allows you to add Tailwind CSS plugins.
  // These plugins can add new utility classes, components, or base styles.
  plugins: [],
}
