// Finalproject/client/src/App.tsx
// Generated by AI (This comment is fine to keep)
import { useState } from 'react'; // Only useState is needed now
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
import './App.css';
import './index.css'; // Ensure index.css is imported for Tailwind

function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      {/* Tailwind CSS Test Area - Retained for general styling check */}
      <div className="text-red-500 p-4 rounded-lg shadow-md mb-4 bg-gray-100">
        <h1 className="text-3xl font-bold underline mb-2">
          Hello Tailwind!
        </h1>
        <p>This text should be red and have padding. If it is, Tailwind CSS is working.</p>
      </div>

      {/* Original Vite/React Boilerplate */}
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  );
}

export default App;
