from functools import wraps
from flask import abort
from flask_login import current_user

# Generated by AI
def role_required(*roles):
    def decorator(f):
        @wraps(f)
        def wrapper(*args, **kwargs):
            if not current_user.is_authenticated:
                abort(401, description="Login required")
            if current_user.role not in roles:
                abort(403, description="You do not have access to this resource")
            return f(*args, **kwargs)
        return wrapper
    return decorator
